export const CONTACT_LIST = "Contacts"
export const CONTACT_DETAILS = "Contacts detail"
export const CREATE_CONTACT = "Contacts Contact"
export const SETTINGS = "Settings"
export const LOGIN = "Login"
export const REGISTER = "Register"
export const HOME_NAVIGATOR = "Home"